name: Test Xbot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: xbot-env

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-mock
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create credentials.json
        run: echo "${{ secrets.FIRE_CREDENTIALS }}" | base64 --decode > $GITHUB_WORKSPACE/credentials.json
      - name: Run tests
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          NUMBER_FROM: ${{ secrets.NUMBER_FROM }}
          NUMBER_TO: ${{ secrets.NUMBER_TO }}
          X_BEARERTOKEN: ${{ secrets.X_BEARERTOKEN }}
          X_APIKEY: ${{ secrets.X_APIKEY }}
          X_APISECRET: ${{ secrets.X_APISECRET }}
          X_TOKEN: ${{ secrets.X_TOKEN }}
          X_TOKENSECRET: ${{ secrets.X_TOKENSECRET }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: pytest src
