name: Xbot Flow

on:
  schedule:
    - cron: '42 08 * * *'
    - cron: '46 11 * * *'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main
      run: |
        python main.py
    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@v5
