name: Xbot Flow

on:
  schedule:
    - cron: "00 00 * * *"
    - cron: "46 14 * * *"
    - cron: "46 19 * * *"
    - cron: "46 21 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: xbot-env

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run main
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          NUMBER_FROM: ${{ secrets.NUMBER_FROM }}
          NUMBER_TO: ${{ secrets.NUMBER_TO }}
          X_BEARERTOKEN: ${{ secrets.X_BEARERTOKEN }}
          X_APIKEY: ${{ secrets.X_APIKEY }}
          X_APISECRET: ${{ secrets.X_APISECRET }}
          X_TOKEN: ${{ secrets.X_TOKEN }}
          X_TOKENSECRET: ${{ secrets.X_TOKENSECRET }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          echo "${{ secrets.FIRE_CREDENTIALS }}" | base64 --decode > $GITHUB_WORKSPACE/fire_credentials.json
          python main.py
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
